"""Safelyn Systems · Inspection-Ready Snapshot PDF.

A single, on-demand inspection-ready PDF that managers can hand to a regulator
(Ofsted for children's homes, CQC for adult services). Auto-detects the service
mix and includes both Ofsted and CQC sections when both are active.
"""
from __future__ import annotations

import io
import hashlib
from datetime import datetime
from typing import Optional, List

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
)


BRAND_DEEP = colors.HexColor("#0F2A47")
BRAND_TEAL = colors.HexColor("#1E4D5C")
GOLD = colors.HexColor("#B8772F")
URGENT_RED = colors.HexColor("#B23A48")
INK = colors.HexColor("#1C1C1A")
INK_2 = colors.HexColor("#575752")
INK_3 = colors.HexColor("#8A8A85")
LINE = colors.HexColor("#D6D6D0")
SAFE_GREEN = colors.HexColor("#3A5A40")
WARN_AMBER = colors.HexColor("#D4A373")


def _hash(payload: dict) -> str:
    src = "|".join([
        str(payload.get("generated_at", "")),
        str(payload.get("generated_by", "")),
        str(payload.get("counts", "")),
    ])
    return hashlib.sha256(src.encode("utf-8")).hexdigest()[:12].upper()


def _format_uk(iso: Optional[str]) -> str:
    if not iso:
        return "—"
    try:
        dt = datetime.fromisoformat(str(iso).replace("Z", "+00:00"))
        return dt.strftime("%a, %d %b %Y · %H:%M")
    except Exception:
        return str(iso)


def _styles():
    base = getSampleStyleSheet()
    return {
        "h1": ParagraphStyle("h1", parent=base["Heading1"], fontName="Helvetica-Bold",
                             fontSize=22, leading=26, textColor=INK, spaceAfter=2),
        "subtitle": ParagraphStyle("subtitle", parent=base["Normal"], fontName="Helvetica",
                                   fontSize=9, textColor=INK_2, leading=12, spaceAfter=10),
        "section": ParagraphStyle("section", parent=base["Heading2"], fontName="Helvetica-Bold",
                                  fontSize=13, leading=16, textColor=BRAND_TEAL,
                                  spaceAfter=4, spaceBefore=10),
        "subsection": ParagraphStyle("subsection", parent=base["Heading3"], fontName="Helvetica-Bold",
                                     fontSize=10, leading=12, textColor=BRAND_DEEP,
                                     spaceAfter=4, spaceBefore=8),
        "label": ParagraphStyle("label", parent=base["Normal"], fontName="Helvetica-Bold",
                                fontSize=8, textColor=INK_3, leading=10),
        "value": ParagraphStyle("value", parent=base["Normal"], fontName="Helvetica",
                                fontSize=10, textColor=INK, leading=14),
        "metric_lbl": ParagraphStyle("metric_lbl", parent=base["Normal"], fontName="Helvetica-Bold",
                                     fontSize=7, textColor=INK_3, leading=9),
        "metric_val": ParagraphStyle("metric_val", parent=base["Normal"], fontName="Helvetica-Bold",
                                     fontSize=22, textColor=INK, leading=24),
        "body": ParagraphStyle("body", parent=base["Normal"], fontName="Helvetica",
                               fontSize=10, textColor=INK, leading=14, spaceAfter=6),
        "muted": ParagraphStyle("muted", parent=base["Normal"], fontName="Helvetica",
                                fontSize=8, textColor=INK_3, leading=11),
    }


def _draw_header_footer(canvas, doc, *, generated_at, generated_by, audit_hash, scope_label):
    canvas.saveState()
    width, height = A4

    canvas.setFillColor(BRAND_DEEP)
    canvas.rect(0, height - 22 * mm, width, 22 * mm, stroke=0, fill=1)
    canvas.setFillColor(GOLD)
    canvas.rect(0, height - 24 * mm, width, 2 * mm, stroke=0, fill=1)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 12)
    canvas.drawString(18 * mm, height - 9 * mm, "Safelyn Systems · INSPECTION-READY SNAPSHOT")
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(colors.HexColor("#E8C994"))
    canvas.drawString(18 * mm, height - 13 * mm, scope_label)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 8)
    canvas.drawRightString(width - 18 * mm, height - 9 * mm, "REGULATORY SNAPSHOT")
    canvas.setFont("Courier", 8)
    canvas.setFillColor(colors.HexColor("#E8C994"))
    canvas.drawRightString(width - 18 * mm, height - 13 * mm, generated_at)

    # footer
    canvas.setFont("Helvetica", 7.5)
    canvas.setFillColor(INK_3)
    canvas.drawString(18 * mm, 12 * mm, f"Generated by {generated_by} · Safelyn Systems")
    canvas.setFont("Courier", 7)
    canvas.drawString(18 * mm, 8 * mm, f"Audit hash: {audit_hash}")
    canvas.setFont("Helvetica", 7.5)
    canvas.drawCentredString(width / 2.0, 12 * mm, "CONFIDENTIAL · Regulator-only")
    canvas.drawString(width - 60 * mm, 12 * mm, f"Page {doc.page}")
    canvas.setStrokeColor(LINE)
    canvas.setLineWidth(0.5)
    canvas.line(18 * mm, 16 * mm, width - 18 * mm, 16 * mm)
    canvas.restoreState()


def _metric_card(label, value, sub=None, tone=None):
    s = _styles()
    tone_color = tone or BRAND_TEAL
    cell = Table([
        [Paragraph(label.upper(), s["metric_lbl"])],
        [Paragraph(str(value), s["metric_val"])],
        [Paragraph(sub or "", s["muted"])],
    ], colWidths=[34 * mm])
    cell.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#FAF7F2")),
        ("LINEBEFORE", (0, 0), (0, -1), 2, tone_color),
        ("BOX", (0, 0), (-1, -1), 0.5, LINE),
        ("LEFTPADDING", (0, 0), (-1, -1), 7),
        ("RIGHTPADDING", (0, 0), (-1, -1), 7),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    return cell


def _row_table(items):
    """Build a row of metric cards (4 across)."""
    rows = [items]
    t = Table(rows, colWidths=[44 * mm] * len(items))
    t.setStyle(TableStyle([
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    return t


def _list_table(headers, rows, col_widths):
    s = _styles()
    if not rows:
        return Paragraph("None recorded.", s["muted"])
    data = [[Paragraph(h.upper(), s["label"]) for h in headers]]
    for r in rows:
        data.append([Paragraph(str(c) if c is not None else "—", s["value"]) for c in r])
    t = Table(data, colWidths=col_widths, repeatRows=1)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F8F7F2")),
        ("BOX", (0, 0), (-1, -1), 0.5, LINE),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, LINE),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    return t


def build_inspection_snapshot_pdf(*, payload: dict, generated_by: str) -> io.BytesIO:
    """Build the Inspection-Ready Snapshot PDF.

    payload structure:
      {
        "scope": "ofsted" | "cqc" | "both",
        "generated_at": ISO,
        "service_mix": [{label, count}],
        "counts": {open_safeguarding, recent_incidents_7d, open_missing,
                   mar_completeness_pct, missed_doses_24h, statutory_visits_overdue,
                   statutory_visits_next14d, handovers_24h, residents_with_no_note_24h,
                   outstanding_actions, ofsted_self_rating, cqc_five_kqs},
        "recent_incidents": [...],
        "open_missing_episodes": [...],
        "outstanding_actions": [...],
      }
    """
    buf = io.BytesIO()
    s = _styles()
    counts = payload.get("counts") or {}
    scope = payload.get("scope") or "both"
    scope_label = {
        "ofsted": "OFSTED · CHILDREN'S HOMES REGULATORY READINESS",
        "cqc": "CQC · ADULT SERVICES REGULATORY READINESS",
        "both": "OFSTED + CQC · COMBINED REGULATORY READINESS",
    }.get(scope, "REGULATORY READINESS")
    generated_at = _format_uk(payload.get("generated_at"))
    audit_hash = _hash({"generated_at": generated_at, "generated_by": generated_by, "counts": counts})

    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=18 * mm, rightMargin=18 * mm,
        topMargin=32 * mm, bottomMargin=22 * mm,
        title=f"Inspection-Ready Snapshot · {generated_at}",
        author="Safelyn Systems",
        subject="Inspection-Ready Snapshot",
    )
    story = []

    # Title
    story.append(Paragraph("<b>Inspection-Ready Snapshot</b>", s["h1"]))
    story.append(Paragraph(
        f"Generated for <b>{generated_by}</b> · {generated_at} · Scope: <b>{scope.upper()}</b>",
        s["subtitle"],
    ))

    # Service mix
    mix = payload.get("service_mix") or []
    if mix:
        story.append(Paragraph("SERVICE MIX", s["subsection"]))
        rows = [[m.get("label"), m.get("count")] for m in mix]
        story.append(_list_table(["Service", "Residents"], rows, [120 * mm, 54 * mm]))
        story.append(Spacer(1, 4 * mm))

    # Headline metrics
    story.append(Paragraph("HEADLINE METRICS", s["section"]))
    metrics_row1 = [
        _metric_card("Open safeguarding", counts.get("open_safeguarding", 0),
                     "Need manager review",
                     URGENT_RED if counts.get("open_safeguarding", 0) else SAFE_GREEN),
        _metric_card("Open missing", counts.get("open_missing", 0),
                     "Currently unaccounted for",
                     URGENT_RED if counts.get("open_missing", 0) else SAFE_GREEN),
        _metric_card("Incidents (7d)", counts.get("recent_incidents_7d", 0),
                     "Across all residents", BRAND_TEAL),
        _metric_card("MAR complete", f"{counts.get('mar_completeness_pct', 100)}%",
                     "Last 24h doses signed",
                     SAFE_GREEN if counts.get("mar_completeness_pct", 100) >= 95 else WARN_AMBER),
    ]
    story.append(_row_table(metrics_row1))
    story.append(Spacer(1, 3 * mm))

    metrics_row2 = [
        _metric_card("Missed doses 24h", counts.get("missed_doses_24h", 0),
                     "Awaiting sign-off",
                     URGENT_RED if counts.get("missed_doses_24h", 0) else SAFE_GREEN),
        _metric_card("Visits overdue", counts.get("statutory_visits_overdue", 0),
                     "Statutory / IRO / SW",
                     URGENT_RED if counts.get("statutory_visits_overdue", 0) else SAFE_GREEN),
        _metric_card("Visits next 14d", counts.get("statutory_visits_next14d", 0),
                     "Planned & on track", BRAND_TEAL),
        _metric_card("Handovers 24h", counts.get("handovers_24h", 0),
                     "Audit-locked", BRAND_TEAL),
    ]
    story.append(_row_table(metrics_row2))
    story.append(Spacer(1, 3 * mm))

    metrics_row3 = [
        _metric_card("Residents w/out note 24h", counts.get("residents_with_no_note_24h", 0),
                     "Daily-care evidence gap",
                     URGENT_RED if counts.get("residents_with_no_note_24h", 0) else SAFE_GREEN),
        _metric_card("Outstanding actions", counts.get("outstanding_actions", 0),
                     "Across the home",
                     WARN_AMBER if counts.get("outstanding_actions", 0) else SAFE_GREEN),
        _metric_card("Risk reviews due", counts.get("risk_reviews_overdue", 0),
                     "Past review date",
                     URGENT_RED if counts.get("risk_reviews_overdue", 0) else SAFE_GREEN),
        _metric_card("Doc reviews due", counts.get("document_reviews_overdue", 0),
                     "Risk asses., plans, etc.",
                     URGENT_RED if counts.get("document_reviews_overdue", 0) else SAFE_GREEN),
    ]
    story.append(_row_table(metrics_row3))

    # Open missing episodes
    om = payload.get("open_missing_episodes") or []
    story.append(Paragraph("OPEN MISSING EPISODES", s["section"]))
    om_rows = [[e.get("resident_name"), _format_uk(e.get("reported_at")),
                e.get("last_seen_location") or "—", e.get("police_reference") or "—"]
               for e in om]
    story.append(_list_table(
        ["Young person", "Reported at", "Last seen", "Police ref"],
        om_rows,
        [42 * mm, 38 * mm, 50 * mm, 44 * mm],
    ))

    # Recent incidents
    inc = payload.get("recent_incidents") or []
    story.append(Paragraph("RECENT INCIDENTS · LAST 7 DAYS", s["section"]))
    inc_rows = [[
        _format_uk(i.get("created_at")),
        (i.get("incident_type") or i.get("category") or "—").upper(),
        (i.get("severity") or "").upper(),
        "SG" if i.get("safeguarding") else "—",
        i.get("resident_name") or "—",
    ] for i in inc[:10]]
    story.append(_list_table(
        ["When", "Type", "Severity", "SG", "Resident"],
        inc_rows,
        [38 * mm, 36 * mm, 22 * mm, 18 * mm, 60 * mm],
    ))

    # Outstanding actions
    actions = payload.get("outstanding_actions_list") or []
    story.append(Paragraph("OUTSTANDING ACTIONS", s["section"]))
    a_rows = [[a.get("title"), a.get("owner"), a.get("due") or "—",
               a.get("category") or "—"] for a in actions[:12]]
    story.append(_list_table(
        ["Action", "Owner", "Due", "Category"],
        a_rows,
        [78 * mm, 32 * mm, 28 * mm, 36 * mm],
    ))

    # Regulator self-rating
    story.append(PageBreak())
    if scope in ("ofsted", "both"):
        story.append(Paragraph("OFSTED — CHILDREN'S HOMES SELF-RATING", s["section"]))
        ofs = (payload.get("ofsted_self_rating") or {})
        ofsted_rows = [
            ("Overall effectiveness", (ofs.get("overall") or "—").title()),
            ("Help & protection", (ofs.get("protection") or "—").title()),
            ("Care", (ofs.get("care") or "—").title()),
            ("Education / progress", (ofs.get("education") or "—").title()),
            ("Leadership & management", (ofs.get("leadership") or "—").title()),
        ]
        story.append(_list_table(["Domain", "Self-rating"], ofsted_rows,
                                 [80 * mm, 94 * mm]))
        story.append(Spacer(1, 4 * mm))

    if scope in ("cqc", "both"):
        story.append(Paragraph("CQC — ADULT SERVICES FIVE KEY QUESTIONS", s["section"]))
        kqs = payload.get("cqc_five_kqs") or []
        kq_rows = [[k.get("label"), (k.get("status") or "—").replace("_", " ").title()] for k in kqs]
        story.append(_list_table(["Key question", "Self-rating"], kq_rows,
                                 [80 * mm, 94 * mm]))

    # Footer note
    story.append(Spacer(1, 8 * mm))
    story.append(Paragraph(
        "<i>This snapshot is generated live from Safelyn Systems data and represents the home's "
        "self-assessed regulatory readiness at the time stamped above. All figures are derived from "
        "audited records (incidents, MAR, statutory visits, handovers, missing episodes, and document "
        "reviews) and are immutable in the source system.</i>",
        s["muted"],
    ))

    doc.build(
        story,
        onFirstPage=lambda c, d: _draw_header_footer(c, d, generated_at=generated_at,
                                                     generated_by=generated_by,
                                                     audit_hash=audit_hash,
                                                     scope_label=scope_label),
        onLaterPages=lambda c, d: _draw_header_footer(c, d, generated_at=generated_at,
                                                      generated_by=generated_by,
                                                      audit_hash=audit_hash,
                                                      scope_label=scope_label),
    )
    buf.seek(0)
    return buf
