"""Safelyn Systems · Ofsted Inspection Bundle PDF.

A single-page bundle inspectors expect at the door: cover page with the
live readiness score, then concise sections — recent incidents (30d),
current MAR snapshot, open/recent missing episodes, overdue actions —
all stapled into one immutable, audit-hashed PDF.
"""
from __future__ import annotations

import io
import hashlib
from datetime import datetime
from typing import List, Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.lib.enums import TA_LEFT
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
)


BRAND_DEEP = colors.HexColor("#0E3B4A")
BRAND_TEAL = colors.HexColor("#0E3B4A")
ACCENT = colors.HexColor("#D65A3A")
URGENT = colors.HexColor("#A8273A")
WARN = colors.HexColor("#B8772F")
SAFE = colors.HexColor("#2F6A3A")
INK = colors.HexColor("#0F1115")
INK_2 = colors.HexColor("#2F3038")
INK_3 = colors.HexColor("#5D6068")
LINE = colors.HexColor("#E2E3DF")
PAPER = colors.HexColor("#FFFFFF")
SOFT = colors.HexColor("#F7F7F5")


def _short(s: str) -> str:
    return f"#{str(s or '').replace('-', '').upper()[-8:]}" if s else "—"


def _audit(payload: dict) -> str:
    src = "|".join(str(v) for v in payload.values())
    return hashlib.sha256(src.encode("utf-8")).hexdigest()[:12].upper()


def _styles():
    base = getSampleStyleSheet()
    return {
        "h1": ParagraphStyle("h1", parent=base["Heading1"], fontName="Helvetica-Bold",
                             fontSize=24, leading=28, textColor=INK, spaceAfter=2),
        "h2": ParagraphStyle("h2", parent=base["Heading2"], fontName="Helvetica-Bold",
                             fontSize=14, leading=18, textColor=INK, spaceBefore=14, spaceAfter=6),
        "section": ParagraphStyle("section", parent=base["Heading3"], fontName="Helvetica-Bold",
                                  fontSize=10, leading=12, textColor=BRAND_TEAL,
                                  spaceAfter=4, spaceBefore=10),
        "subtitle": ParagraphStyle("subtitle", parent=base["Normal"], fontName="Helvetica",
                                   fontSize=9.5, textColor=INK_2, leading=13, spaceAfter=10),
        "label": ParagraphStyle("label", parent=base["Normal"], fontName="Helvetica-Bold",
                                fontSize=8, textColor=INK_3, leading=10),
        "value": ParagraphStyle("value", parent=base["Normal"], fontName="Helvetica",
                                fontSize=10, textColor=INK, leading=14),
        "body": ParagraphStyle("body", parent=base["Normal"], fontName="Helvetica",
                               fontSize=10, textColor=INK_2, leading=14, alignment=TA_LEFT, spaceAfter=4),
        "small": ParagraphStyle("small", parent=base["Normal"], fontName="Helvetica",
                                fontSize=8.5, textColor=INK_2, leading=11),
        "muted": ParagraphStyle("muted", parent=base["Normal"], fontName="Helvetica",
                                fontSize=8.5, textColor=INK_3, leading=11),
        "score_huge": ParagraphStyle("score_huge", parent=base["Heading1"], fontName="Helvetica-Bold",
                                     fontSize=68, leading=72, textColor=INK, alignment=1),
        "score_label": ParagraphStyle("score_label", parent=base["Normal"], fontName="Helvetica-Bold",
                                      fontSize=9, leading=11, textColor=INK_3, alignment=1),
    }


def _draw_header_footer(canvas, doc, *, ref, generated_at, audit_hash):
    canvas.saveState()
    width, height = A4
    canvas.setFillColor(BRAND_DEEP)
    canvas.rect(0, height - 18 * mm, width, 18 * mm, stroke=0, fill=1)
    canvas.setFillColor(ACCENT)
    canvas.rect(0, height - 20 * mm, width, 2 * mm, stroke=0, fill=1)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 11)
    canvas.drawString(18 * mm, height - 8.5 * mm, "Safelyn Systems · INSPECTION BUNDLE")
    canvas.setFont("Helvetica", 7.5)
    canvas.setFillColor(colors.HexColor("#9DB5C2"))
    canvas.drawString(18 * mm, height - 13 * mm, "OFSTED-READY · POLICE-READY · IMMUTABLE AUDIT TRAIL")
    canvas.setFillColor(colors.white)
    canvas.setFont("Courier", 8)
    canvas.drawRightString(width - 18 * mm, height - 8.5 * mm, ref)
    canvas.setFont("Courier", 7)
    canvas.setFillColor(colors.HexColor("#C8D4DC"))
    canvas.drawRightString(width - 18 * mm, height - 13 * mm, audit_hash)

    canvas.setFont("Helvetica", 7.5)
    canvas.setFillColor(INK_3)
    canvas.drawString(18 * mm, 11 * mm, f"Generated by Safelyn Systems · {generated_at}")
    canvas.drawCentredString(width / 2.0, 11 * mm, ref)
    canvas.drawString(width - 40 * mm, 11 * mm, f"Page {doc.page}")
    canvas.setStrokeColor(LINE)
    canvas.setLineWidth(0.4)
    canvas.line(18 * mm, 14 * mm, width - 18 * mm, 14 * mm)
    canvas.restoreState()


def _kv(rows, col_widths=None):
    s = _styles()
    data = []
    for label, value in rows:
        data.append([
            Paragraph(label.upper(), s["label"]),
            Paragraph(str(value or "—"), s["value"]),
        ])
    t = Table(data, colWidths=col_widths or [50 * mm, 124 * mm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), SOFT),
        ("BOX", (0, 0), (-1, -1), 0.5, LINE),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, LINE),
        ("LEFTPADDING", (0, 0), (-1, -1), 7),
        ("RIGHTPADDING", (0, 0), (-1, -1), 7),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    return t


def _score_color(score: int):
    if score >= 75:
        return SAFE
    if score >= 60:
        return WARN
    return URGENT


def build_inspection_bundle_pdf(
    *,
    readiness: dict,
    incidents: List[dict],
    medications: List[dict],
    mar_admins: List[dict],
    missing_episodes: List[dict],
    residents_by_id: dict,
    generated_for: str,
    period_label: str,
) -> io.BytesIO:
    buf = io.BytesIO()
    ref = _short(f"BNDL{int(datetime.utcnow().timestamp())}")
    generated_at = datetime.utcnow().strftime("%a, %d %b %Y · %H:%M UTC")
    audit_hash = _audit({
        "ref": ref,
        "overall": readiness.get("overall"),
        "incidents": len(incidents),
        "meds": len(medications),
        "missing": len(missing_episodes),
    })

    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=18 * mm, rightMargin=18 * mm,
        topMargin=24 * mm, bottomMargin=18 * mm,
        title=f"Inspection Bundle · {period_label}",
        author="Safelyn Systems",
        subject="Ofsted Inspection Bundle",
    )
    s = _styles()
    story = []

    # ---- Cover page: live score ----
    story.append(Paragraph("Ofsted Inspection Bundle", s["h1"]))
    story.append(Paragraph(
        f"Period: <b>{period_label}</b> &nbsp;·&nbsp; Prepared for: <b>{generated_for}</b>",
        s["subtitle"],
    ))

    overall = int(readiness.get("overall", 0))
    rating = (readiness.get("rating") or {}).get("label", "—")
    score_color = _score_color(overall)
    score_table = Table(
        [
            [Paragraph(f"<font color='{score_color.hexval()}' size='68'><b>{overall}</b></font>"
                       f"<br/><font color='#5D6068' size='9'><b>OVERALL READINESS · LIVE</b></font>",
                       s["body"]),
             Paragraph(
                 f"<font color='{score_color.hexval()}' size='14'><b>{rating}</b></font><br/><br/>"
                 f"This bundle stitches together the live Ofsted Readiness scorecard, the last 30 days "
                 f"of incidents, the current Medication Administration Record, all open or recent "
                 f"missing-from-care episodes, and outstanding compliance actions. Every record is "
                 f"time-stamped and cryptographically hashed. Reference {ref} · audit {audit_hash}.",
                 s["body"]),
             ],
        ],
        colWidths=[48 * mm, 126 * mm],
    )
    score_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), SOFT),
        ("BOX", (0, 0), (-1, -1), 0.5, LINE),
        ("LEFTPADDING", (0, 0), (-1, -1), 12),
        ("RIGHTPADDING", (0, 0), (-1, -1), 12),
        ("TOPPADDING", (0, 0), (-1, -1), 12),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(score_table)
    story.append(Spacer(1, 4 * mm))

    # Section breakdown
    story.append(Paragraph("Compliance breakdown", s["h2"]))
    rows = [[Paragraph("AREA", s["label"]), Paragraph("SCORE", s["label"]), Paragraph("STATUS", s["label"])]]
    for sec in readiness.get("sections", []):
        sc = int(sec.get("score", 0))
        col = _score_color(sc)
        rows.append([
            Paragraph(sec.get("title", "—"), s["value"]),
            Paragraph(f"<font color='{col.hexval()}'><b>{sc}/100</b></font>", s["value"]),
            Paragraph(sec.get("summary", "—"), s["small"]),
        ])
    t = Table(rows, colWidths=[60 * mm, 28 * mm, 86 * mm], repeatRows=1)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), SOFT),
        ("BOX", (0, 0), (-1, -1), 0.5, LINE),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, LINE),
        ("LEFTPADDING", (0, 0), (-1, -1), 7),
        ("RIGHTPADDING", (0, 0), (-1, -1), 7),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    story.append(t)

    story.append(PageBreak())

    # ---- Recent incidents ----
    story.append(Paragraph(f"Incidents · last 30 days ({len(incidents)})", s["h2"]))
    if not incidents:
        story.append(Paragraph("No incidents recorded in the period.", s["muted"]))
    else:
        rows = [[
            Paragraph("WHEN", s["label"]),
            Paragraph("RESIDENT", s["label"]),
            Paragraph("TYPE / SEVERITY", s["label"]),
            Paragraph("SUMMARY", s["label"]),
        ]]
        for inc in incidents[:30]:
            kind = (inc.get("incident_type") or inc.get("category") or "—").upper()
            sev = (inc.get("severity") or "").upper()
            tag = f"{kind} · {sev}" + (" · SG" if inc.get("safeguarding") else "")
            short = (inc.get("structured_report") or inc.get("body") or "")[:200]
            if len(inc.get("structured_report") or inc.get("body") or "") > 200:
                short += "…"
            rid = inc.get("resident_id")
            r_name = (residents_by_id.get(rid) or {}).get("name", "—")
            when = (inc.get("created_at") or "")[:16].replace("T", " ")
            rows.append([
                Paragraph(when, s["small"]),
                Paragraph(r_name, s["small"]),
                Paragraph(tag, s["small"]),
                Paragraph(short, s["small"]),
            ])
        t = Table(rows, colWidths=[28 * mm, 32 * mm, 36 * mm, 78 * mm], repeatRows=1)
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), SOFT),
            ("BOX", (0, 0), (-1, -1), 0.5, LINE),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, LINE),
            ("LEFTPADDING", (0, 0), (-1, -1), 5),
            ("RIGHTPADDING", (0, 0), (-1, -1), 5),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        story.append(t)

    # ---- Medications snapshot ----
    story.append(Paragraph(f"Active medications ({len(medications)})", s["h2"]))
    if not medications:
        story.append(Paragraph("No active medications.", s["muted"]))
    else:
        rows = [[
            Paragraph("RESIDENT", s["label"]),
            Paragraph("MEDICATION", s["label"]),
            Paragraph("DOSE / SCHEDULE", s["label"]),
            Paragraph("PRESCRIBER", s["label"]),
        ]]
        for m in medications:
            r_name = (residents_by_id.get(m.get("resident_id")) or {}).get("name", "—")
            sched = "PRN" if m.get("is_prn") else ", ".join(m.get("schedule_times") or [])
            rows.append([
                Paragraph(r_name, s["small"]),
                Paragraph(m.get("name", "—") + (" ⚠" if m.get("allergy_warning") else ""), s["small"]),
                Paragraph(f"{m.get('dose','—')} · {sched}", s["small"]),
                Paragraph(m.get("prescriber") or "—", s["small"]),
            ])
        t = Table(rows, colWidths=[36 * mm, 50 * mm, 50 * mm, 38 * mm], repeatRows=1)
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), SOFT),
            ("BOX", (0, 0), (-1, -1), 0.5, LINE),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, LINE),
            ("LEFTPADDING", (0, 0), (-1, -1), 5),
            ("RIGHTPADDING", (0, 0), (-1, -1), 5),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        story.append(t)
    story.append(Paragraph(
        f"<i>{len(mar_admins)} administration records signed in the last 7 days. "
        f"Full MAR PDFs available per resident from the Safelyn dashboard.</i>",
        s["muted"],
    ))

    # ---- Missing episodes ----
    story.append(Paragraph(f"Missing-from-care episodes ({len(missing_episodes)})", s["h2"]))
    if not missing_episodes:
        story.append(Paragraph("No missing-from-care episodes in the period. ✓", s["muted"]))
    else:
        rows = [[
            Paragraph("REPORTED", s["label"]),
            Paragraph("RESIDENT", s["label"]),
            Paragraph("STATUS", s["label"]),
            Paragraph("DETAIL", s["label"]),
        ]]
        for ep in missing_episodes[:20]:
            r_name = (residents_by_id.get(ep.get("resident_id")) or {}).get("name", "—")
            status = "RETURNED" if ep.get("returned_at") else "OPEN"
            color = SAFE if ep.get("returned_at") else URGENT
            detail = ep.get("last_seen_location") or "—"
            rows.append([
                Paragraph((ep.get("reported_at") or "")[:16].replace("T", " "), s["small"]),
                Paragraph(r_name, s["small"]),
                Paragraph(f"<font color='{color.hexval()}'><b>{status}</b></font>", s["small"]),
                Paragraph(detail, s["small"]),
            ])
        t = Table(rows, colWidths=[34 * mm, 36 * mm, 28 * mm, 76 * mm], repeatRows=1)
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), SOFT),
            ("BOX", (0, 0), (-1, -1), 0.5, LINE),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, LINE),
            ("LEFTPADDING", (0, 0), (-1, -1), 5),
            ("RIGHTPADDING", (0, 0), (-1, -1), 5),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        story.append(t)

    # Footer
    story.append(Spacer(1, 8 * mm))
    story.append(Paragraph(
        f"<i>Immutable inspection bundle generated by Safelyn Systems for {generated_for}. "
        f"Reference {ref}. Audit hash {audit_hash}. "
        f"Each component (incidents, MAR, missing pack, scorecard) is independently exportable for verification.</i>",
        s["muted"],
    ))

    doc.build(
        story,
        onFirstPage=lambda c, d: _draw_header_footer(c, d, ref=ref, generated_at=generated_at, audit_hash=audit_hash),
        onLaterPages=lambda c, d: _draw_header_footer(c, d, ref=ref, generated_at=generated_at, audit_hash=audit_hash),
    )
    buf.seek(0)
    return buf
