"""Safelyn Systems · Medication Administration Record (MAR) PDF.

Weekly grid showing each medication × each scheduled time × each day,
with administration status (G=given, R=refused, M=missed, W=withheld,
S=self-administered).
"""
from __future__ import annotations

import io
import os
import hashlib
from datetime import datetime, timedelta
from typing import Optional, List

import qrcode
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.utils import ImageReader
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    KeepTogether,
)


BRAND_DEEP = colors.HexColor("#0F2A47")
BRAND_TEAL = colors.HexColor("#1E4D5C")
ACCENT_TERRACOTTA = colors.HexColor("#E57A5D")
URGENT_RED = colors.HexColor("#B23A48")
SAFE_GREEN = colors.HexColor("#3A5A40")
WARN_AMBER = colors.HexColor("#D4A373")
INK = colors.HexColor("#1C1C1A")
INK_2 = colors.HexColor("#575752")
INK_3 = colors.HexColor("#8A8A85")
LINE = colors.HexColor("#D6D6D0")

STATUS_LETTER = {
    "given": "G",
    "refused": "R",
    "missed": "M",
    "withheld": "W",
    "self-administered": "S",
    "not-required": "N",
}
STATUS_COLOR = {
    "given": SAFE_GREEN,
    "refused": URGENT_RED,
    "missed": URGENT_RED,
    "withheld": WARN_AMBER,
    "self-administered": BRAND_TEAL,
    "not-required": INK_3,
}


def _ref(rid: str) -> str:
    cleaned = str(rid or "").replace("-", "").upper()
    return f"#{cleaned[-8:]}" if cleaned else "—"


def _audit_hash(payload: dict) -> str:
    src = "|".join([str(payload.get(k, "")) for k in ("resident_id", "from_date", "to_date")])
    return hashlib.sha256(src.encode("utf-8")).hexdigest()[:12].upper()


def _styles():
    base = getSampleStyleSheet()
    return {
        "h1": ParagraphStyle("h1", parent=base["Heading1"], fontName="Helvetica-Bold",
                             fontSize=20, leading=24, textColor=INK, spaceAfter=2),
        "subtitle": ParagraphStyle("subtitle", parent=base["Normal"], fontName="Helvetica",
                                   fontSize=9, textColor=INK_2, leading=12, spaceAfter=8),
        "section": ParagraphStyle("section", parent=base["Heading3"], fontName="Helvetica-Bold",
                                  fontSize=10, leading=12, textColor=BRAND_TEAL,
                                  spaceAfter=4, spaceBefore=8),
        "label": ParagraphStyle("label", parent=base["Normal"], fontName="Helvetica-Bold",
                                fontSize=7.5, textColor=INK_3, leading=10),
        "value": ParagraphStyle("value", parent=base["Normal"], fontName="Helvetica",
                                fontSize=9, textColor=INK, leading=12),
        "small": ParagraphStyle("small", parent=base["Normal"], fontName="Helvetica",
                                fontSize=7, textColor=INK_2, leading=9),
        "muted": ParagraphStyle("muted", parent=base["Normal"], fontName="Helvetica",
                                fontSize=7, textColor=INK_3, leading=9),
        "ref_mono": ParagraphStyle("ref_mono", parent=base["Normal"], fontName="Courier-Bold",
                                   fontSize=10, textColor=BRAND_TEAL),
    }


def _draw_header(canvas, doc, *, ref, generated_at, audit_hash):
    canvas.saveState()
    width, height = landscape(A4)
    canvas.setFillColor(BRAND_DEEP)
    canvas.rect(0, height - 18 * mm, width, 18 * mm, stroke=0, fill=1)
    canvas.setFillColor(ACCENT_TERRACOTTA)
    canvas.rect(0, height - 20 * mm, width, 2 * mm, stroke=0, fill=1)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 11)
    canvas.drawString(15 * mm, height - 8 * mm, "Safelyn Systems · MAR CHART")
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(colors.HexColor("#9DB5C2"))
    canvas.drawString(15 * mm, height - 12 * mm, "MEDICATION ADMINISTRATION RECORD · WEEKLY")
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 8)
    canvas.drawRightString(width - 15 * mm, height - 8 * mm, ref)
    canvas.setFont("Courier", 7)
    canvas.setFillColor(colors.HexColor("#C8D4DC"))
    canvas.drawRightString(width - 15 * mm, height - 12 * mm, audit_hash)
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(INK_3)
    canvas.drawString(15 * mm, 8 * mm, f"Generated by Safelyn Systems · {generated_at}")
    canvas.drawCentredString(width / 2.0, 8 * mm, ref)
    canvas.drawString(width - 40 * mm, 8 * mm, f"Page {doc.page}")
    canvas.setStrokeColor(LINE)
    canvas.line(15 * mm, 11 * mm, width - 15 * mm, 11 * mm)
    canvas.restoreState()


def _date_range_iter(from_date: str, to_date: str):
    a = datetime.strptime(from_date, "%Y-%m-%d").date()
    b = datetime.strptime(to_date, "%Y-%m-%d").date()
    cur = a
    while cur <= b:
        yield cur
        cur = cur + timedelta(days=1)


def build_mar_pdf(
    *,
    resident: dict,
    medications: List[dict],
    admins: List[dict],
    from_date: str,
    to_date: str,
    generated_for: str,
) -> io.BytesIO:
    buf = io.BytesIO()
    ref = _ref(resident.get("id", ""))
    generated_at = datetime.utcnow().strftime("%a, %d %b %Y · %H:%M UTC")
    audit_hash = _audit_hash({"resident_id": resident.get("id"), "from_date": from_date, "to_date": to_date})

    doc = SimpleDocTemplate(
        buf, pagesize=landscape(A4),
        leftMargin=12 * mm, rightMargin=12 * mm,
        topMargin=24 * mm, bottomMargin=18 * mm,
        title=f"MAR · {resident.get('name','—')} · {from_date}→{to_date}",
        author="Safelyn Systems",
        subject="Medication Administration Record",
    )
    s = _styles()
    story = []

    res_name = resident.get("name", "—")
    story.append(Paragraph(
        f"<b>MAR Chart</b> &nbsp;<font color='#8A8A85' size='12'>{res_name}</font>", s["h1"]
    ))
    story.append(Paragraph(
        f"Period {from_date} → {to_date} · DOB {resident.get('dob') or '—'} · "
        f"NHS {(resident.get('medical') or {}).get('nhs_number') or '—'} · "
        f"Allergies: <b>{(resident.get('medical') or {}).get('allergies') or '—'}</b>",
        s["subtitle"],
    ))

    # Build a key-lookup of admins
    admin_key = {(a["medication_id"], a["scheduled_at"]): a for a in admins}

    # For each med, render a table: rows = scheduled times, cols = days
    days = list(_date_range_iter(from_date, to_date))
    if not medications:
        story.append(Paragraph("No active medications.", s["muted"]))
    for med in medications:
        is_prn = bool(med.get("is_prn"))
        title = (
            f"<b>{med['name']}</b> · {med['dose']} · {med.get('route') or 'Oral'}"
            + (" · <font color='#E57A5D'><b>PRN</b></font>" if is_prn else "")
        )
        story.append(Paragraph(title, s["section"]))
        if med.get("instructions"):
            story.append(Paragraph(med["instructions"], s["muted"]))
        if med.get("allergy_warning"):
            story.append(Paragraph(
                f"<font color='#B23A48'><b>ALERT:</b> {med['allergy_warning']}</font>",
                s["muted"],
            ))

        if is_prn:
            # PRN table: list of administrations in the period
            prn_rows = sorted(
                [a for a in admins if a.get("medication_id") == med["id"]],
                key=lambda a: a.get("scheduled_at") or "",
            )
            if not prn_rows:
                story.append(Paragraph("No PRN doses given in this period.", s["muted"]))
            else:
                rows = [[
                    Paragraph("WHEN", s["label"]),
                    Paragraph("DOSE", s["label"]),
                    Paragraph("STATUS", s["label"]),
                    Paragraph("BY", s["label"]),
                    Paragraph("NOTES", s["label"]),
                ]]
                for a in prn_rows:
                    rows.append([
                        Paragraph(a.get("administered_at", "")[:16].replace("T", " "), s["small"]),
                        Paragraph(a.get("dose_given") or med["dose"], s["small"]),
                        Paragraph(a.get("status", "—").upper(), s["small"]),
                        Paragraph(a.get("administered_by_name") or "—", s["small"]),
                        Paragraph(a.get("notes") or "—", s["small"]),
                    ])
                t = Table(rows, colWidths=[42 * mm, 28 * mm, 26 * mm, 36 * mm, 130 * mm])
                t.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F8F7F2")),
                    ("BOX", (0, 0), (-1, -1), 0.4, LINE),
                    ("INNERGRID", (0, 0), (-1, -1), 0.4, LINE),
                    ("LEFTPADDING", (0, 0), (-1, -1), 4),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                    ("TOPPADDING", (0, 0), (-1, -1), 3),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ]))
                story.append(t)
        else:
            times = med.get("schedule_times", []) or []
            if not times:
                story.append(Paragraph("No schedule set.", s["muted"]))
                continue
            head = [Paragraph("TIME", s["label"])] + [
                Paragraph(d.strftime("%a %d/%m"), s["label"]) for d in days
            ]
            rows = [head]
            for t in times:
                row = [Paragraph(t, s["value"])]
                for d in days:
                    try:
                        hh, mn = t.split(":")
                        sched_dt = datetime(d.year, d.month, d.day, int(hh), int(mn))
                        sched_iso = sched_dt.isoformat() + "+00:00"
                        a = admin_key.get((med["id"], sched_iso))
                    except Exception:
                        a = None
                    if a:
                        letter = STATUS_LETTER.get(a.get("status"), "?")
                        cell = Paragraph(
                            f"<font color='#{STATUS_COLOR.get(a.get('status'), INK).hexval()[2:]}' size='9'><b>{letter}</b></font>"
                            f"<br/><font color='#8A8A85' size='6'>{(a.get('administered_by_name') or '')[:12]}</font>",
                            s["small"],
                        )
                    else:
                        cell = Paragraph("—", s["muted"])
                    row.append(cell)
                rows.append(row)
            col_w = [22 * mm] + [
                (260 * mm - 22 * mm) / len(days) for _ in days
            ]
            t = Table(rows, colWidths=col_w, repeatRows=1)
            t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F8F7F2")),
                ("BOX", (0, 0), (-1, -1), 0.4, LINE),
                ("INNERGRID", (0, 0), (-1, -1), 0.4, LINE),
                ("LEFTPADDING", (0, 0), (-1, -1), 3),
                ("RIGHTPADDING", (0, 0), (-1, -1), 3),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("ALIGN", (1, 1), (-1, -1), "CENTER"),
            ]))
            story.append(t)
        story.append(Spacer(1, 3 * mm))

    # Legend
    story.append(Spacer(1, 4 * mm))
    legend = (
        "<b>Key:</b> "
        "<font color='#3A5A40'><b>G</b></font> Given · "
        "<font color='#B23A48'><b>R</b></font> Refused · "
        "<font color='#B23A48'><b>M</b></font> Missed · "
        "<font color='#D4A373'><b>W</b></font> Withheld · "
        "<font color='#1E4D5C'><b>S</b></font> Self-administered · "
        "<font color='#8A8A85'><b>N</b></font> Not required"
    )
    story.append(Paragraph(legend, s["muted"]))

    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph(
        f"<i>Immutable audit record generated by Safelyn Systems for {generated_for}. "
        f"Reference {ref}. Audit hash {audit_hash}.</i>",
        s["muted"],
    ))

    doc.build(
        story,
        onFirstPage=lambda c, d: _draw_header(c, d, ref=ref, generated_at=generated_at, audit_hash=audit_hash),
        onLaterPages=lambda c, d: _draw_header(c, d, ref=ref, generated_at=generated_at, audit_hash=audit_hash),
    )
    buf.seek(0)
    return buf
