"""Safelyn Systems · Return Interview PDF.

Police-and-LA-friendly PDF capturing the formal Return Interview that follows
a missing-from-care episode (Working Together / statutory guidance).
"""
from __future__ import annotations

import io
import hashlib
from datetime import datetime
from typing import Optional, List

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)


BRAND_DEEP = colors.HexColor("#0F2A47")
BRAND_TEAL = colors.HexColor("#1E4D5C")
URGENT_RED = colors.HexColor("#B23A48")
INK = colors.HexColor("#1C1C1A")
INK_2 = colors.HexColor("#575752")
INK_3 = colors.HexColor("#8A8A85")
LINE = colors.HexColor("#D6D6D0")
SAFE_GREEN = colors.HexColor("#3A5A40")


def _short_ref(rid: str) -> str:
    cleaned = str(rid or "").replace("-", "").upper()
    return f"#{cleaned[-8:]}" if cleaned else "—"


def _audit_hash(payload: dict) -> str:
    src = "|".join([
        str(payload.get("id", "")),
        str(payload.get("conducted_at", "")),
        str(payload.get("resident_id", "")),
        str(payload.get("conducted_by_name", "")),
    ])
    return hashlib.sha256(src.encode("utf-8")).hexdigest()[:12].upper()


def _format_uk(iso: Optional[str]) -> str:
    if not iso:
        return "—"
    try:
        dt = datetime.fromisoformat(str(iso).replace("Z", "+00:00"))
        return dt.strftime("%a, %d %b %Y · %H:%M")
    except Exception:
        return str(iso)


def _styles():
    base = getSampleStyleSheet()
    return {
        "h1": ParagraphStyle("h1", parent=base["Heading1"], fontName="Helvetica-Bold",
                             fontSize=20, leading=24, textColor=INK, spaceAfter=2),
        "subtitle": ParagraphStyle("subtitle", parent=base["Normal"], fontName="Helvetica",
                                   fontSize=9, textColor=INK_2, leading=12, spaceAfter=10),
        "section": ParagraphStyle("section", parent=base["Heading3"], fontName="Helvetica-Bold",
                                  fontSize=10, leading=12, textColor=BRAND_TEAL,
                                  spaceAfter=4, spaceBefore=10),
        "label": ParagraphStyle("label", parent=base["Normal"], fontName="Helvetica-Bold",
                                fontSize=8, textColor=INK_3, leading=10),
        "value": ParagraphStyle("value", parent=base["Normal"], fontName="Helvetica",
                                fontSize=10, textColor=INK, leading=14),
        "body": ParagraphStyle("body", parent=base["Normal"], fontName="Helvetica",
                               fontSize=10, textColor=INK, leading=14, spaceAfter=6),
        "muted": ParagraphStyle("muted", parent=base["Normal"], fontName="Helvetica",
                                fontSize=8, textColor=INK_3, leading=11),
    }


def _draw_header_footer(canvas, doc, *, ref, generated_at, audit_hash):
    canvas.saveState()
    width, height = A4

    canvas.setFillColor(BRAND_DEEP)
    canvas.rect(0, height - 22 * mm, width, 22 * mm, stroke=0, fill=1)
    canvas.setFillColor(BRAND_TEAL)
    canvas.rect(0, height - 24 * mm, width, 2 * mm, stroke=0, fill=1)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 12)
    canvas.drawString(18 * mm, height - 9 * mm, "Safelyn Systems · RETURN INTERVIEW")
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(colors.HexColor("#C9D6DD"))
    canvas.drawString(18 * mm, height - 13 * mm, "MISSING FROM CARE FOLLOW-UP · STATUTORY")
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 8)
    canvas.drawRightString(width - 18 * mm, height - 9 * mm, "RETURN INTERVIEW")
    canvas.setFont("Courier", 8)
    canvas.setFillColor(colors.HexColor("#C9D6DD"))
    canvas.drawRightString(width - 18 * mm, height - 13 * mm, ref)

    # footer
    canvas.setFont("Helvetica", 7.5)
    canvas.setFillColor(INK_3)
    canvas.drawString(18 * mm, 12 * mm, f"Generated by Safelyn Systems · {generated_at}")
    canvas.setFont("Courier", 7)
    canvas.drawString(18 * mm, 8 * mm, f"Audit hash: {audit_hash}")
    canvas.setFont("Helvetica", 7.5)
    canvas.drawCentredString(width / 2.0, 12 * mm, ref)
    canvas.drawString(width - 60 * mm, 12 * mm, f"Page {doc.page}")
    canvas.setStrokeColor(LINE)
    canvas.setLineWidth(0.5)
    canvas.line(18 * mm, 16 * mm, width - 18 * mm, 16 * mm)
    canvas.restoreState()


def _kv(rows, col_widths=None):
    s = _styles()
    data = []
    for label, value in rows:
        data.append([
            Paragraph(label.upper(), s["label"]),
            Paragraph(value or "—", s["value"]),
        ])
    t = Table(data, colWidths=col_widths or [50 * mm, 124 * mm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8F7F2")),
        ("BOX", (0, 0), (-1, -1), 0.5, LINE),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, LINE),
        ("LEFTPADDING", (0, 0), (-1, -1), 7),
        ("RIGHTPADDING", (0, 0), (-1, -1), 7),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    return t


def _bullets(items):
    s = _styles()
    if not items:
        return Paragraph("—", s["muted"])
    return Paragraph("<br/>".join(f"• {str(i)}" for i in items), s["body"])


def build_return_interview_pdf(
    *,
    interview: dict,
    resident: dict,
    episode: Optional[dict] = None,
) -> io.BytesIO:
    buf = io.BytesIO()
    ref = _short_ref(interview.get("id", ""))
    generated_at = datetime.utcnow().strftime("%a, %d %b %Y · %H:%M UTC")
    audit_hash = _audit_hash(interview)

    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=18 * mm, rightMargin=18 * mm,
        topMargin=32 * mm, bottomMargin=22 * mm,
        title=f"Return Interview · {resident.get('name','Resident')} · {ref}",
        author="Safelyn Systems",
        subject="Missing From Care · Return Interview",
    )
    s = _styles()
    story = []

    # Title block
    story.append(Paragraph(
        f"<b>Return Interview</b> &nbsp;&nbsp;<font color='#8A8A85' size='12'>{ref}</font>",
        s["h1"],
    ))
    story.append(Paragraph(
        f"Conducted: <b>{_format_uk(interview.get('conducted_at'))}</b>"
        f"  ·  Returned to placement: <b>{_format_uk(interview.get('returned_at'))}</b>"
        f"  ·  Status: <b>{(interview.get('status') or 'submitted').upper()}</b>",
        s["subtitle"],
    ))

    # Identification
    story.append(_kv([
        ("Young person", resident.get("name")),
        ("Date of birth", resident.get("dob")),
        ("Placement", resident.get("local_authority") or resident.get("placement_summary")),
        ("Conducted by", interview.get("conducted_by_name")),
        ("Episode reference", _short_ref(interview.get("missing_episode_id") or "")),
        ("Reported missing at", _format_uk((episode or {}).get("reported_at"))),
    ]))

    # Account of events
    story.append(Paragraph("YOUNG PERSON'S ACCOUNT OF EVENTS", s["section"]))
    story.append(Paragraph(interview.get("account_of_events") or "—", s["body"]))

    # Locations
    story.append(Paragraph("LOCATIONS VISITED", s["section"]))
    story.append(_bullets(interview.get("locations_visited") or []))

    # People
    story.append(Paragraph("WHO THEY WERE WITH", s["section"]))
    story.append(_bullets(interview.get("who_they_were_with") or []))

    # Safeguarding
    story.append(Paragraph("SAFEGUARDING CONCERNS", s["section"]))
    story.append(Paragraph(interview.get("safeguarding_concerns") or "None reported.", s["body"]))

    # Exploitation indicators
    indicators = interview.get("exploitation_indicators") or []
    story.append(Paragraph("CHILD EXPLOITATION INDICATORS", s["section"]))
    if indicators:
        story.append(_bullets(indicators))
    else:
        story.append(Paragraph("None identified during interview.", s["muted"]))

    # Actions taken
    story.append(Paragraph("ACTIONS TAKEN", s["section"]))
    story.append(Paragraph(interview.get("actions_taken") or "—", s["body"]))

    # Follow-up
    story.append(Paragraph("FOLLOW-UP REQUIRED", s["section"]))
    story.append(Paragraph(interview.get("follow_up_required") or "—", s["body"]))

    # Manager sign-off
    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph("MANAGER REVIEW & SIGN-OFF", s["section"]))
    if interview.get("signed_off_by_name"):
        story.append(_kv([
            ("Signed off by", interview.get("signed_off_by_name")),
            ("Signed off at", _format_uk(interview.get("signed_off_at"))),
            ("Manager comments", interview.get("manager_comments")),
        ]))
    else:
        story.append(Paragraph(
            "<font color='#B23A48'><b>Awaiting manager sign-off.</b></font>",
            s["body"],
        ))

    # Audit footer
    story.append(Spacer(1, 6 * mm))
    story.append(Paragraph(
        f"<i>Immutable Return Interview record generated by Safelyn Systems. "
        f"Reference {ref}. Conducted by "
        f"{interview.get('conducted_by_name','—')} on "
        f"{_format_uk(interview.get('conducted_at'))}.</i>",
        s["muted"],
    ))

    doc.build(
        story,
        onFirstPage=lambda c, d: _draw_header_footer(c, d, ref=ref, generated_at=generated_at, audit_hash=audit_hash),
        onLaterPages=lambda c, d: _draw_header_footer(c, d, ref=ref, generated_at=generated_at, audit_hash=audit_hash),
    )
    buf.seek(0)
    return buf
